---
# handlers file for opensearch

- name: Stopping Docker
  ansible.builtin.service:
    name: docker
    state: stopped

- name: Starting Docker
  ansible.builtin.service:
    name: docker
    state: started

- name: Restart Docker
  ansible.builtin.service:
    name: docker
    state: restarted

- name: Sync docker
  ansible.posix.synchronize:
    src: /var/lib/docker
    dest: /docker
    archive: true
  delegate_to: "{{ inventory_hostname }}"