---

- name: Configure firewall for OpenSearch
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Ensure UFW is installed
      apt:
        name: ufw
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Ensure UFW is enabled
      ufw:
        state: enabled
      when: ansible_distribution == "Ubuntu"

    - name: Allow OpenSearch port 22
      ufw:
        rule: allow
        port: 22
      when: ansible_distribution == "Ubuntu"

    - name: Allow OpenSearch port 9200
      ufw:
        rule: allow
        port: 9200
      when: ansible_distribution == "Ubuntu"

- name: Opensearch installation & configuration
  hosts: all
  gather_facts: true
  become: true
  roles:
    - role: linux/opensearch

  tasks:
    - name: Ensure Java is installed
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Set JAVA_HOME environment variable
      lineinfile:
        path: /etc/environment
        line: 'JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64'
        create: yes

    - name: Reload environment variables
      shell: source /etc/environment

    - name: Adjust JVM options for OpenSearch (initial heap size)
      lineinfile:
        path: /usr/share/opensearch/config/jvm.options
        regexp: '^(-Xms)'
        line: '-Xms1g'
        state: present

    - name: Adjust JVM options for OpenSearch (max heap size)
      lineinfile:
        path: /usr/share/opensearch/config/jvm.options
        regexp: '^(-Xmx)'
        line: '-Xmx1g'
        state: present

    - name: Start and enable OpenSearch
      systemd:
        name: opensearch
        state: started
        enabled: true

    - name: Wait for OpenSearch to startup
      wait_for:
        port: 9200
        host: "{{ ansible_host }}"
        delay: 10
        timeout: 600

- name: Opensearch dashboards installation & configuration
  hosts: ungrouped
  gather_facts: true
  become: true
  roles:
    - role: linux/dashboards

  tasks:
    - name: Start and enable OpenSearch Dashboards
      systemd:
        name: opensearch-dashboards
        state: started
        enabled: true

    - name: Wait for OpenSearch Dashboards to startup
      wait_for:
        port: 5601
        host: "{{ ansible_host }}"
        delay: 10
        timeout: 600